#!/bin/bash
#=================================================#
#SCRIPT MONTADO POR: ELIJAHSSH
#=================================================#
clear
[[ "$(whoami)" != "root" ]] && {
    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
    rm $HOME/bottestee >/dev/null 2>&1
    exit 0
}
_lnk='15.228.127.48'; _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
function verif_key() {
    krm=$(echo '5:q-3gs2.o7%8:1' | rev)
    chmod +x $_Ink/list >/dev/null 2>&1
    [[ ! -e "$_Ink/list" ]] && {
        echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
        rm -rf $HOME/Plus >/dev/null 2>&1
        sleep 2
        clear
        exit 1
    }
}
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[44;1;37m        LICENÇA BOT TESTE  by: Elijahssh       \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \033[1;31mATENCAO! \033[1;37mEXECULTAR O COMANDO \033[1;33m(bottestee!)\033[0m"
echo ""
echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×[\033[1;33m • \033[1;32mBY:@ELIJAHSSH\033[1;33m •\033[1;31m ]≠×≠×≠×≠×≠×≠×≠×\033[0m"
echo ""
echo -ne "\033[1;36mINFORME SUA KEY:\033[1;37m "; read key
_lnk2=$(echo "$key"|awk -F : '{print $2}'); _lnk1=$(echo "$key"|awk -F : '{print $1}')
echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m $key\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink $_lnk/$_lnk1/$_lnk2/list > /dev/null 2>&1; verif_key
echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 1s
clear
installbot () {
clear
echo -e "\E[44;1;37m     INSTALACAO BOT SSH TESTE     \E[0m"
echo -e "\nINSTALANDO AGUARDE...."
apt update -y > /dev/null 2>&1 && apt install unzip at jq curl -y > /dev/null 2>&1
mkdir $HOME/BOT
cd $HOME/BOT && wget https://www.dropbox.com/s/q0oinerayzoefu4/botteste1.0.zip
unzip botteste1.0.zip > /dev/null 2>&1 && rm botteste1.0.zip > /dev/null 2>&1
chmod +x $(ls)
mv bottestee /bin/bottestee
cd $HOME && rm inst-bottestee > /dev/null 2>&1
echo -e "\033[1;32m BOT TESTE INSTALADO!"
rm -rf $HOME/.wget-hsts > /dev/null 2>&1
sleep 3
bottestee
}
nbot () {
clear
screen -r -S "bot_teste" -X quit
clear && echo "BOT DESATIVADO"
menu
}
sbot () {
clear
clear
[[ $(screen -list| grep -c 'bot_teste') == '0' ]] && {
    clear
    echo -e "\E[44;1;37m     ATIVACÃO BOT SSH TESTE     \E[0m"
    echo ""
    echo -ne "\033[1;31m====PREENCHA AS INFORMACOES DO BOT===="
    echo ""
    echo ""
    echo -ne "\033[1;32mMENSAGEM DO ADM:\033[1;37m "
    read bvindo
    clear
    echo -ne "\033[1;32mMENSAGEM FINAL:\033[1;37m "
    read mfinal
    clear
    echo -ne "\033[1;32mNOME DO BOTÃO 1(GERADOR SSH):\033[1;37m "
    read bt1
    clear
    echo -ne "\033[1;32mNOME DO BOTÃO 2(PERSONALIZADO):\033[1;37m "
    read bt2
    echo -ne "\033[1;32mLINK DO BOTÃO 2 (Ex: www.google.com): \033[1;37m "
    read link2
    clear
    echo -ne "\033[1;32mNOME DO BOTÃO 3(PERSONALIZADO):\033[1;37m "
    read bt3
    echo -ne "\033[1;32mLINK DO BOTÃO 3 (Ex: www.google.com):\033[1;37m "
    read link3
    clear
    echo -ne "\033[1;32mNOME DO BOTÃO 4 (BOTAO DE PAGAMENTO PIX):\033[1;37m "
    read bt4
    echo -ne "\033[1;32mVALOR DO PIX (EX: R$ 15,00):\033[1;37m "
    read vl1
    echo -ne "\033[1;32mCHAVE PIX (QUALQUER TIPO DE CHAVE):\033[1;37m "
    read pi1
    clear
    echo -ne "\033[1;32mDURAÇÃO DO TESTE(EM HORAS):\033[1;37m "
    read dtempo
    clear
    sed -i "s/INFO_ADM/$bvindo/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    sed -i "s/MSG_FINAL/$mfinal/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    sed -i "s/BT_INF01/$bt1/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    sed -i "s/INF02_BT/$bt2/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    sed -i "s/LINK_BT02/$link2/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    sed -i "s/BNT03_BT/$bt3/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    sed -i "s/LK_BT03/$link3/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    sed -i "s/BN_BT04/$bt4/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    sed -i "s/VALOR_PIX/$vl1/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    sed -i "s/CHAVE_PIX/$pi1/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    sed -i "s/TEMPO_TESTE/$dtempo/g" $HOME/BOT/botsshteste >/dev/null 2>&1
    clear
    echo -ne "\n\033[1;32mINFORME O TOKEN\033[1;37m: "; read token
    cd $HOME/BOT
    screen -dmS bot_teste ./botsshteste $token > /dev/null 2>&1
    clear && echo "BOT ATIVADO"
    menu
} || {
    screen -r -S "bot_teste" -X quit
    clear && echo "BOT DESATIVADO"
    menu
}
}
newbot () {
    clear
    rm -rf $HOME/BOT > /dev/null 2>&1
    echo -e "\033[1;32m BOT TESTE REMOVIDO!"
    sleep 3
    clear
}
while true $x != "ok"
do
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[44;1;37m        INSTALADOR BOT TESTE  by: Elijahssh       \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;31m ANTES DE ATIVAR O BOT, PRIMEIRO INSTALE NA OPCAO 1"
echo ""
echo -e "\033[1;31m  [\033[1;36m 01 \033[1;31m] \033[1;37m• \033[1;33mINSTALAR BOT TESTE"
echo -e "\033[1;31m  [\033[1;36m 02 \033[1;31m] \033[1;37m• \033[1;33mATIVAR BOT TESTE"
echo -e "\033[1;31m  [\033[1;36m 03 \033[1;31m] \033[1;37m• \033[1;33mREMOVER BOT TESTE"
echo -e "\033[1;31m  [\033[1;36m 04 \033[1;31m] \033[1;37m• \033[1;33mDESATIVAR BOT TESTE"
echo -e "\033[1;31m  [\033[1;36m 00 \033[1;31m] \033[1;37m• \033[1;33mSAIR"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""
echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;31m?\033[1;37m : "; read x

case "$x" in 
   1 | 01)
   clear
   installbot
   ;;
   2 | 02)
   clear
   sbot
   ;;
   3 | 03)
   clear
   newbot
   ;;
    4 | 04)
   clear
   nbot
   ;;
   0 | 00)
   echo -e "\033[1;31mSaindo...\033[0m"
   sleep 2
   clear
   exit;
   ;;
   *)
   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
   sleep 2
esac
done
}
#fim
